artifactory-repo: hpeartifacts-docker-harmony-local.jfrog.io
artifactory-user: sahil.sawhney@hpe.com
# artifactory-password: Provided as -p
helm-test-app-namespace: test-app-helm
helm-test-app-release: test-app
helm-test-app-image: hpeartifacts-docker-harmony-local.jfrog.io/akka-http-quickstart-scala:lihas
kustomize-test-app-namespace: test-app-kustomize