apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-app-kustomize

resources:
  - ../../base

replicas:
  - name: user-management-kustomize-deployment
    count: 3

images:
  - name: OVERRIDE_ME
    newName: hpeartifacts-docker-harmony-local.jfrog.io/akka-http-quickstart-scala
    newTag: lihas
