apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ Values.app-name }}-deployment
  namespace: {{ Values.namespace }}
spec:
  selector:
    matchLabels:
      app: my-helm-app
  replicas: {{ Values.replica }}
  template:
    metadata:
      labels:
        app: my-helm-app
    spec:
      containers:
      - name: app
        image: {{ Values.image }}
        ports:
        - containerPort: 8080