apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-cluster-role
rules:
- apiGroups: ["*"]
  resources:
  - pods
  - pods/exec
  - secrets
  - ingresses
  - services
  - jobs
  - deployments
  - statefulsets
  - cronjobs
  - workflows
  - configmaps
  verbs: ["*"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: argo
    namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-cluster-role
  apiGroup: rbac.authorization.k8s.io
