apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-kustomize-deployment
  namespace: OVERRIDE_ME 
spec:
  selector:
    matchLabels:
      app: my-kustomize-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-kustomize-app
    spec:
      containers:
      - name: app
        image: OVERRIDE_ME
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: test-regcred