apiVersion: v1
kind: Service
metadata:
  name: user-management-kustomize-service
  namespace: OVERRIDE_ME
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: my-kustomize-app